# Auto-updated Jamboree list: list3

list3 = {
    "Aggressive OR Argumentative": [
        "Bellicose {Magoosh, Majortest, Princeton}",
        "Belligerent {Barron, Magoosh, Majortest}",
        "Contentious {Magoosh, Majortest, Manhattan, Princeton}",
        "Disputatious",
        "Fractious {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Hostility",
        "Litigious",
        "Polemical {Majortest, Princeton}",
        "Pugnacious {Barron, Magoosh, Majortest, Manhattan}",
        "Truculent {Magoosh, Manhattan, Princeton}",
        "controversial",
        "inveigh",
        "polemic",
        "truculence",
        "vehement",
        "vehemently",
    ],
    "Aggressive OR Argumentative (Noisy)": [
        "unruly",
    ],
    "Agreement OR Harmony": [
        "Accord",
        "Concord",
        "Conformity",
        "Congruous",
        "Consonance",
        "Discord(Opposite) {Magoosh, Majortest}",
        "Dissonance(Opposite) {Kaplan, Majortest, Manhattan}",
        "Faction(Opposite) {Manhattan}",
        "Incompatible(Opposite)",
        "Discrepancy(Opposite) {Majortest, Manhattan}",
        "Irreconcilable(Opposite)",
        "clique",
        "cohesive",
        "collusion",
        "compatible",
        "complementary",
        "mutual agreement",
        "coterie",
    ],
    "Agreement OR Harmony (Discussion)": [
        "powwow",
    ],
    "Argue OR Fight": [
        "Altercation",
        "Bicker",
        "Brawl {Barron}",
        "Combat",
        "Contend",
        "Row",
        "Scuffle",
        "Squabble",
        "Tiff",
        "Tussle",
        "Truce(Opposite)",
        "confront",
        "factious",
        "fracas",
        "moot",
        "polemic",
        "strife",
        "vie",
        "embroiled",
        "internecine",
        "recrimination",
    ],
    "Argue OR Fight (Reply)": [
        "retort",
    ],
    "Argue OR Fight (Argument)": [
        "unconscionable",
    ],
    "Argue OR Fight (Small)": [
        "skirmish",
    ],
    "Being Alike": [
        "Homogeneity {Majortest}",
        "Uniformity",
        "Heterogeneity(Opposite)",
        "analogous",
    ],
    "Being Alike (Same Kind)": [
        "homogeneous",
    ],
    "Biased": [
        "Bigot {Barron, Majortest}",
        "Discriminatory",
        "Prejudiced",
        "Partisan {Majortest, Manhattan}",
        "Disinterested(Opposite) {Magoosh, Majortest, Manhattan, Princeton}",
        "Tendentious {Magoosh, Majortest, Manhattan, Princeton}",
        "bias",
        "chauvinist",
        "jingoist",
        "nepotism",
        "gerrymander",
    ],
    "Bite": [
        "masticate",
    ],
    "Calm": [
        "Aplomb {Magoosh}",
        "Composure",
        "Equanimity {Barron, Manhattan}",
        "Impassive {Manhattan, Princeton}",
        "Imperturbable {Barron, Kaplan, Manhattan, Princeton}",
        "Nonchalant {Magoosh}",
        "Phlegmatic {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Placid {Magoosh, Majortest, Manhattan}",
        "Serene {Magoosh, Majortest}",
        "Staid {Magoosh, Majortest}",
        "Stolid {Kaplan, Magoosh, Majortest, Manhattan}",
        "Tranquil {Barron, Majortest}",
        "bromide",
        "sangfroid",
        "sedate",
        "serenity",
        "unflappable",
        "repose",
    ],
    "Cynical": [
        "cynic",
    ],
    "Clemency": [
        "clemency",
    ],
    "Confuse": [
        "Astound",
        "Baffle",
        "Befuddle {Majortest}",
        "Bemuse",
        "Bewilder",
        "Confound {Magoosh, Majortest, Manhattan}",
        "Flabbergasted {Barron}",
        "Foxed",
        "Nonplussed {Magoosh, Majortest, Princeton}",
        "Obfuscated",
        "Perplex",
        "Stupefy {Princeton}",
        "flummox",
    ],
    "Disturbed OR Agitated": [
        "Consternation {Barron, Majortest}",
        "Disconcert",
        "Dismay",
        "Distraught {Barron}",
        "Faze",
        "Fluster",
        "Frenetic {Barron, Kaplan, Manhattan}",
        "Hysterical",
        "Implacable {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Overwrought {Kaplan, Majortest, Manhattan}",
        "Perturb {Magoosh}",
        "Disquiet",
        "paroxysm",
        "tempestuous",
        "tumult",
        "turbulent",
    ],
    "Dominating(-)": [
        "Absolute",
        "Authoritative",
        "Autocrat",
        "Despot {Magoosh}",
        "Dogmatic {Kaplan, Magoosh, Majortest, Princeton}",
        "Hegemony {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Imperious {Magoosh, Manhattan}",
        "Martinet {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Totalitarian",
        "Tyrant",
        "Doctrinaire {Kaplan, Manhattan}",
        "ascendancy",
        "autocratic",
        "dictatorial",
        "magisterial",
        "omnipotent",
        "peremptory",
        "potentate",
        "puissant",
        "arch",
    ],
    "Easily noticeable": [
        "Patent {Magoosh, Manhattan}",
        "Conspicuous {Magoosh, Majortest}",
        "Prominent {Majortest}",
        "appreciable",
        "manifest",
    ],
    "Easily noticeable (Touch)": [
        "tangible",
    ],
    "Equality": [
        "Commensurate {Magoosh, Majortest, Manhattan}",
        "Parity {Majortest}",
        "Peers",
        "Disparate(Opposite) {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Tantamount {Barron, Magoosh}",
        "constituent",
    ],
    "Masculinity": [
        "machismo",
    ],
    "Inequity": [
        "inequity",
    ],
    "Futility": [
        "futility",
    ],
    "Excessive Flattery": [
        "Fawn {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Fulsome {Barron}",
        "Obsequious {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Sycophant {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Adulation {Majortest, Princeton}",
        "inordinate",
    ],
    "Excessive Physical": [
        "obese",
    ],
    "Impartial": [
        "Dispassionate {Magoosh, Majortest, Manhattan}",
        "Egalitarian {Manhattan}",
        "Equitable {Magoosh, Manhattan}",
        "Evenhanded {Magoosh}",
        "Objectivity",
        "impartial",
    ],
    "Artifact": [
        "artifact",
    ],
    "Sabbatical": [
        "sabbatical",
    ],
    "Irrational": [
        "irrational",
    ],
    "Fatal": [
        "fatal",
    ],
    "Include Everything": [
        "Comprehensive {Barron}",
        "Encompass",
        "Expansive {Magoosh}",
        "Pervasive {Majortest, Manhattan, Princeton}",
        "catholic",
        "comprehensive",
        "gamut",
    ],
    "Include Everything (Universal)": [
        "universal",
    ],
    "Indifferent": [
        "Apathy {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Stoic {Majortest, Manhattan, Princeton}",
        "blase",
        "indifference",
        "insouciance",
    ],
    "Itinerant": [
        "itinerant",
    ],
    "Insulting Words": [
        "Deprecatory",
        "Derogatory {Barron, Majortest}",
        "Pejorative {Kaplan, Magoosh, Majortest, Manhattan}",
        "broadside",
        "execrate",
        "lampoon",
    ],
    "Make Hostile": [
        "Alienate {Manhattan}",
        "Antagonize {Kaplan, Manhattan}",
        "Estrange",
    ],
    "To Make List": [
        "enumerate",
    ],
    "Narrow Minded OR Regional": [
        "Insular {Manhattan}",
        "Myopic {Kaplan, Magoosh, Manhattan}",
        "Parochial {Magoosh, Majortest}",
        "Provincial {Magoosh, Majortest}",
        "blinkered",
    ],
    "Not Serious OR Disrespect": [
        "Flippant {Magoosh, Majortest}",
        "Frivolous OR Frivolity {Magoosh, Majortest}",
        "Insouciant {Princeton}",
        "Levity {Barron, Kaplan, Majortest, Manhattan}",
        "Grave OR Gravity(Opposite)",
        "Blithe {Kaplan, Majortest, Manhattan}",
        "Facetious {Barron, Magoosh, Majortest, Manhattan, Princeton}",
    ],
    "Overly Obedient(-)": [
        "Grovel {Kaplan, Magoosh, Manhattan}",
        "Servile {Barron, Majortest}",
        "Slavish",
        "Subservient {Barron}",
        "Supplicant {Majortest}",
        "cosseted",
        "kowtow",
        "officious",
        "unctuous",
    ],
    "Present Everywhere": [
        "Omnipresent",
        "Ubiquitous {Barron, Majortest, Manhattan, Princeton}",
        "cosmopolitan",
    ],
    "Split OR Gap": [
        "Chasm",
        "Dichotomy {Majortest, Manhattan}",
        "Gulf",
        "Rift {Barron, Manhattan}",
        "Schism {Barron}",
    ],
    "Suppress OR End": [
        "Quash",
        "Quell {Barron, Majortest}",
        "Repress {Barron}",
        "Scotch {Majortest}",
        "Subdue",
        "squelch",
        "stem",
        "stunt",
        "subsume",
    ],
    "Sure OR Certain": [
        "irrefutable",
        "irrevocable",
        "unassailable",
        "unequivocal",
    ],
    "To Come Out From": [
        "Emanate",
        "Emit {Barron}",
    ],
}