# Auto-updated Jamboree list: list11

list11 = {
    "Artificial Or Pretense": [
        "Affected {Kaplan}",
        "Contrived",
        "Mannered {Kaplan, Majortest, Manhattan}",
        "Posture {Majortest}",
        "Pretentious {Majortest, Manhattan}",
        "ostensible",
        "pretext",
        "semblance",
        "simulacrum",
    ],
    "Aware Or Unaware (Opposite)": [
        "Cognizant {Barron}",
        "Oblivious(Opposite) {Majortest}",
    ],
    "Best Example": [
        "Apotheosis {Magoosh, Princeton}",
        "Archetype {Majortest}",
        "Embody",
        "Epitome {Barron}",
        "Exemplify {Magoosh, Majortest}",
        "Paradigm {Majortest, Manhattan}",
        "Paragon {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Personify",
        "Prototype(Neutral)",
        "acme",
        "apex",
        "apogee",
        "exemplar",
        "pinnacle",
        "summit",
        "zenith",
    ],
    "Force Or Put Pressure": [
        "Coercion {Majortest}",
        "Compel",
        "Compulsion {Magoosh}",
        "Extort",
        "Press",
        "Dissuade",
        "besiege",
        "coerce",
        "duress",
    ],
    "Force Or Put Pressure (-)": [
        "exploit",
        "extortion",
        "foist",
    ],
    "Get Rid Of Or Cleanse": [
        "Catharsis {Majortest}",
        "Expurgate {Barron, Kaplan, Magoosh, Manhattan}",
        "Purge",
    ],
    "Go Off Track": [
        "Astray",
        "Awry",
        "Circuitous {Majortest}",
        "Desultory {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Digress {Majortest, Manhattan}",
        "Discursive {Magoosh, Majortest}",
        "Divergent",
        "Ramble {Majortest}",
        "Tangential {Kaplan, Manhattan}",
        "errant",
    ],
    "Go Off Track (Go back)": [
        "revert",
    ],
    "Important Mark": [
        "Hallmark {Manhattan}",
        "Landmark {Barron, Manhattan}",
        "Milestone",
        "Watershed",
        "barometer",
        "nutrition",
        "phenomenon",
    ],
    "Important Mark (Medicine)": [
        "symptomatic",
    ],
    "Important Mark (Physical)": [
        "plaque",
    ],
    "Impure Or Poisonous": [
        "Adulterate {Kaplan, Manhattan, Princeton}",
        "Contaminate",
        "Noxious {Majortest, Princeton}",
        "Toxic",
        "Vitiate {Barron, Majortest, Princeton}",
    ],
    "Inborn Or Firmly Fixed": [
        "Congenital {Majortest}",
        "Entrenched {Magoosh}",
        "Inherent {Barron, Manhattan}",
        "Innate {Barron, Majortest}",
        "Intrinsic {Barron, Manhattan}",
    ],
    "Intelligent Or Wise": [
        "Acuity {Majortest}",
        "Acumen {Manhattan, Princeton}",
        "Astute {Barron, Majortest}",
        "Discerning {Manhattan}",
        "Discriminating {Manhattan}",
        "Insightful",
        "Judicious {Kaplan, Majortest, Manhattan}",
        "Perceptive {Majortest}",
        "Perspicacious {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Prudent {Barron, Majortest, Manhattan}",
        "Sagacious {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Sage {Barron, Majortest}",
        "Savant {Majortest, Manhattan}",
        "Impolitic(Opposite)",
        "Shrewd(Neutral)",
        "Canny",
        "Simpleton(Opposite)",
        "percipient",
        "savvy",
    ],
    "Not Sacred Or Worldly": [
        "Secular {Manhattan}",
        "Temporal",
        "extrinsic",
    ],
    "Not Disposed to Believe": [
        "incredulous",
    ],
    "Persuade Or Flatter": [
        "Cajole {Barron, Majortest}",
        "Coax",
        "Cogent {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Enjoin {Magoosh}",
        "Exhort {Barron, Magoosh}",
        "Induce",
        "Urge",
        "Wheedle {Barron}",
        "Woo(Neutral)",
        "Blandishment {Majortest}",
        "Court",
        "ingratiate",
        "glib",
    ],
    "Plead (Offer)": [
        "proffer",
        "supplication",
        "tender",
    ],
    "Plead": [
        "Behest",
        "Beseech",
        "Entreaty {Barron}",
        "Implore {Barron}",
        "Importune {Barron, Majortest}",
        "Supplicate {Manhattan}",
        "beg",
        "importuned",
        "solicit",
    ],
    "Prove To Be Right": [
        "Gratuitous(Opposite) {Majortest}",
        "Justifiable",
        "Necessitate",
        "Warrant",
        "Indefensible(Opposite)",
        "Untenable(Opposite) {Magoosh, Princeton}",
    ],
    "Prove To Be Right (Reasonable)": [
        "tenable",
    ],
    "Spoil or Disfigure": [
        "Deface {Kaplan, Manhattan}",
        "Distort",
        "Mar {Kaplan, Manhattan}",
        "Warp",
        "Impair {Manhattan}",
        "bastardization",
        "besmirch",
        "maim",
    ],
    "Spotted Or Stained": [
        "Blemish",
        "Debase {Magoosh, Manhattan}",
        "Sully {Kaplan, Manhattan}",
        "Taint {Barron}",
        "Tarnish {Magoosh}",
        "eruption",
    ],
    "Stupid Or Foolish": [
        "Asinine {Barron}",
        "Fatuous {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Imbecile",
        "Inane {Barron}",
        "Oafish",
        "Obtuse {Magoosh, Majortest, Princeton}",
        "benighted",
        "inanity",
    ],
    "Sulking Or Bad Tempered": [
        "Dour",
        "Morose {Magoosh, Majortest, Manhattan, Princeton}",
        "Peevish {Magoosh}",
        "Petulant {Magoosh, Majortest}",
        "Pout",
        "Saturnine {Magoosh, Princeton}",
        "Sullen {Barron, Magoosh}",
        "Surly {Kaplan, Magoosh, Majortest, Manhattan}",
    ],
    "Sulking OR Bad Tempered (Irritable)": [
        "splenetic",
    ],
    "Sulking OR Bad Tempered": [
        "begrudge",
        "bilious",
        "fret",
        "inebriated",
    ],
    "Tempt Or Plot Or Trick(-)": [
        "Allure {Majortest}",
        "Beguile {Majortest}",
        "Collude {Manhattan}",
        "Connive",
        "Conspire",
        "Entice {Magoosh}",
        "Lure",
        "Ploy {Magoosh}",
        "Ruse {Majortest}",
        "Scheme",
        "Tactic",
    ],
    "Tempt OR Plot OR Trick(-) (Teasing)": [
        "tantalizing",
    ],
    "Tempt OR Plot OR Trick(-)": [
        "conniving",
        "finagle",
    ],
    "To See": [
        "Behold",
        "Discern {Barron, Kaplan, Majortest}",
        "Espy",
        "Perceive {Barron}",
        "Imperceptible(Opposite) {Barron}",
        "countenance",
        "depict",
    ],
    "Steep": [
        "steep",
    ],
    "Common Sense": [
        "gumption",
    ],
    "To Inspire": [
        "galvanize",
    ],
    "Uncover A Secret": [
        "Ferret {Magoosh}",
        "Unearth {Manhattan}",
        "Unravel",
        "epiphany",
        "palimpsest",
        "telltale",
    ],
    "Unmatched Or Unique": [
        "Inimitable {Magoosh, Princeton}",
        "Peerless {Majortest}",
        "singular",
    ],
}