# Auto-updated Jamboree list: list4

list4 = {
    "Calm Down(+) Make Better": [
        "Allay {Barron, Majortest}",
        "Alleviate {Barron, Kaplan, Majortest, Manhattan}",
        "Ameliorate {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Appease {Magoosh, Majortest, Manhattan}",
        "Assuage {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Conciliate {Magoosh, Majortest}",
        "Extenuating {Magoosh}",
        "Mitigate {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Mollify {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Pacify",
        "Placate {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Propitiated",
        "Solace {Barron, Majortest}",
        "Temper {Majortest}",
        "Exacerbate(Opposite) {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "rapprochement",
        "reconcile",
    ],
    "Crucial OR Significant": [
        "Core",
        "Foremost",
        "Imperative {Barron, Majortest}",
        "Indispensable",
        "Mandatory",
        "Momentous {Majortest}",
        "Paramount {Barron, Majortest}",
        "Pivotal {Majortest}",
        "Salient {Barron, Kaplan, Manhattan}",
        "Linchpin",
        "moment",
        "pith",
        "portentous",
        "primacy",
    ],
    "Difficult To Understand": [
        "Abstract",
        "Abstruse {Magoosh, Majortest}",
        "Arcane {Magoosh, Majortest, Manhattan}",
        "Esoteric {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Mystical",
        "Obscure {Barron, Magoosh, Majortest}",
        "Occult {Barron, Manhattan, Princeton}",
        "Recondite {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Profound(+) OR Profundity",
        "Perspicuous(Opposite)",
        "implausible",
        "imponderable",
    ],
    "Difficult To Understand (Depth)": [
        "profound",
    ],
    "End OR Stop": [
        "Terminate {Barron}",
        "Culminate {Barron, Magoosh, Manhattan}",
        "Cease",
        "Onset(Opposite)",
        "cessation",
        "desist",
    ],
    "End OR Stop (Terminus)": [
        "terminus",
    ],
    "Used For Variety/Group": [
        "octave",
        "potpourri",
        "raft",
        "repertoire",
        "roster",
        "throng",
    ],
    "Enthusiastic OR Excited": [
        "Arbor OR Ardent",
        "Avid {Barron, Manhattan}",
        "Dynamic {Majortest}",
        "Ebullient {Kaplan, Magoosh, Majortest, Manhattan}",
        "Effervescent {Magoosh}",
        "Effusive {Majortest}",
        "Exuberant",
        "Fervent OR Fervor {Majortest, Princeton}",
        "Frisky",
        "Gushing",
        "Impassioned",
        "Vivacious {Barron}",
        "Zealous OR Zest {Barron, Princeton}",
        "Dampen(Opposite)",
        "Tepid(Opposite)",
        "Rhapsody",
        "ardent",
        "arouse",
        "fervid",
        "gusto",
    ],
    "Happy OR Joyous": [
        "Beam",
        "Ecstasy",
        "Elated {Manhattan}",
        "Euphoria {Magoosh}",
        "Exhilaration",
        "Exultant",
        "Felicity",
        "Gaiety",
        "Jest",
        "Jocular {Kaplan, Magoosh, Majortest, Manhattan}",
        "Jocund",
        "Jollity {Majortest}",
        "Jovial {Magoosh}",
        "Jubilant {Barron, Magoosh, Majortest}",
        "Rapturous",
        "Uproarious {Majortest}",
        "Regale {Majortest}",
        "beatific",
        "bliss",
        "chortle",
        "exult",
        "exultation",
        "guffaw",
        "halcyon",
        "nirvana",
        "winsome",
    ],
    "Hardworking(+)": [
        "Assiduous {Barron, Majortest, Manhattan, Princeton}",
        "Diligent {Magoosh, Majortest}",
        "Industrious {Magoosh}",
        "Painstaking",
        "Sedulous {Magoosh, Majortest, Manhattan, Princeton}",
        "Toil",
        "assiduously",
    ],
    "Irregular OR Periodically": [
        "Fitfully",
        "Intermittent {Majortest}",
        "Occasional",
        "Spasmodic",
        "Sporadic {Barron, Magoosh, Majortest, Manhattan, Princeton}",
    ],
    "Lacking Energy OR Lazy(-)": [
        "Indolent {Barron, Kaplan, Manhattan}",
        "Jaded {Majortest}",
        "Lackadaisical",
        "Lackluster {Majortest, Manhattan}",
        "Languid {Kaplan, Magoosh, Majortest, Manhattan}",
        "Lassitude {Barron, Kaplan, Majortest, Manhattan}",
        "Lethargic {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Listless {Kaplan, Manhattan}",
        "Sloth",
        "Sluggish",
        "Torpor OR Torpid {Kaplan, Magoosh, Majortest, Manhattan}",
        "anemic",
        "inert",
        "languish",
    ],
    "Lacking Energy OR Lazy(-) (Lying)": [
        "supine",
    ],
    "Lacking Energy OR Lazy(-) (Sitting)": [
        "sedentary",
    ],
    "Lacking Energy OR Lazy (Avoid Duty)": [
        "malingerer",
    ],
    "Lacking Energy": [
        "incapacitated",
    ],
    "Never Ending OR Non-Stop": [
        "Chronic {Majortest}",
        "Incessant {Magoosh, Majortest}",
        "Inexorable {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Interminable {Barron, Majortest}",
        "Perennial {Magoosh, Majortest, Manhattan, Princeton}",
        "Relentless",
        "perpetuate",
    ],
    "Ordinary(-)": [
        "Banat",
        "Cliche {Barron, Majortest}",
        "Commonplace",
        "Derivative {Magoosh, Manhattan}",
        "Hackney",
        "Humdrum {Magoosh}",
        "Mundane {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Pedestrian {Magoosh, Majortest, Manhattan, Princeton}",
        "Platitude {Magoosh, Majortest, Manhattan, Princeton}",
        "Plebeian {Kaplan, Manhattan}",
        "Quotidian {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Trite {Magoosh, Majortest, Manhattan}",
        "Unremarkable",
        "abysmal",
        "banal",
        "banality",
        "hackneyed",
        "deplorable",
    ],
    "Ordinary(-) (Formulaic)": [
        "stereotype",
    ],
    "Related": [
        "Affiliated",
        "Kindred",
        "component",
        "concomitant",
        "corollary",
    ],
    "War Related": [
        "martial",
    ],
    "Sad OR Depressed": [
        "Anguish",
        "Bereaved",
        "Bleak {Magoosh}",
        "Crestfallen {Magoosh}",
        "Dejected",
        "Desolate",
        "Despondent {Majortest}",
        "Forlorn {Magoosh}",
        "Glum",
        "Lament {Kaplan, Manhattan}",
        "Lugubrious {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Melancholy",
        "Plaintive {Majortest}",
        "Woe",
        "Pathos {Majortest}",
        "Poignant {Barron, Magoosh, Majortest}",
    ],
    "Show/Express": [
        "evince",
        "gesticulate",
    ],
    "Short Lived": [
        "Ephemeral {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Evanescent {Barron, Magoosh, Majortest, Princeton}",
        "Fleeting {Manhattan}",
        "Transient {Barron, Magoosh, Majortest, Princeton}",
        "Transitory {Kaplan, Magoosh, Manhattan}",
        "meteoric",
        "moribund",
        "passe",
        "sojourn",
        "truncated",
    ],
    "Not Living": [
        "inanimate",
    ],
    "Hoard": [
        "hoard",
    ],
    "Unimportant OR Trivial": [
        "Expendable",
        "Fringe {Majortest, Manhattan}",
        "Incidental",
        "Inconsequential {Majortest, Manhattan}",
        "Marginalization",
        "Peripheral {Majortest, Manhattan}",
        "picayune",
        "trivial",
    ],
    "Unusual OR Exception": [
        "Aberration {Magoosh, Majortest}",
        "Anomaly {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Deviate",
        "aberrant",
        "anomalous",
    ],
    "Unstoppable Force": [
        "juggernaut",
    ],
}