# Auto-updated Jamboree list: list9

list9 = {
    "About To Happen": [
        "Imminent {Barron, Manhattan, Princeton}",
        "Impending(-)",
        "advent",
        "impending",
    ],
    "Careless": [
        "Lax {Barron, Majortest, Manhattan}",
        "Negligent",
        "Remiss {Barron, Magoosh}",
        "Slipshod",
        "Stringent(opposite) {Magoosh, Majortest}",
        "derelict",
        "haphazard",
    ],
    "Confirm Or Declare": [
        "Affirm",
        "Ascertain {Barron, Manhattan}",
        "Assert",
        "Aver {Barron, Majortest, Manhattan, Princeton}",
        "Avow",
        "Contend",
        "Proclaim",
        "Testimony",
        "acknowledge",
        "attest",
        "maintain",
    ],
    "Easily Affected(-)": [
        "Prone {Majortest}",
        "Subject To",
        "Susceptible {Barron, Majortest}",
        "Vulnerable {Barron}",
        "Impervious(opposite) {Kaplan, Magoosh, Manhattan}",
    ],
    "Enter Without Permission": [
        "Encroach",
        "Impinge",
        "Infringe",
        "Intrude",
        "Obtrude",
        "interloper",
    ],
    "Examine Carefully": [
        "Peruse {Barron, Magoosh, Majortest, Princeton}",
        "Pore Over",
        "Scrutinize {Barron, Majortest}",
        "Browse(neutral)",
        "delve",
    ],
    "Examine": [
        "evaluate",
        "interrogate",
    ],
    "Friendly": [
        "Affable {Magoosh, Majortest, Manhattan}",
        "Amiable {Magoosh, Majortest}",
        "Amicable {Barron}",
        "Camaraderie",
        "Complaisance {Majortest, Princeton}",
        "Congenial {Barron}",
        "Convivial {Magoosh}",
        "Cordial",
        "Fraternize",
        "Genial {Magoosh}",
        "Gregarious {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Aloof(opposite) {Barron, Majortest, Manhattan}",
        "Frigid(opposite)",
        "Glacial(opposite) {Majortest, Manhattan}",
        "boon",
        "complaisant",
        "conducive",
    ],
    "Foreign": [
        "expatriate",
    ],
    "Give Up": [
        "Abdicate {Kaplan, Manhattan}",
        "Abjure {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Abnegate",
        "Cede {Magoosh}",
        "Forgo",
        "Forsake",
        "Forswear",
        "Relinquish",
        "Renounce",
    ],
    "Hide Or Cover Or Disguise": [
        "Camouflage",
        "Cloak",
        "Dissemble {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Feign",
        "Guise {Barron}",
        "Incognito",
        "Mask",
        "Masquerade",
        "Shroud",
        "Veneer {Barron, Magoosh, Majortest}",
        "cache",
    ],
    "Imitate Or Comic Imitation(neutral)": [
        "Emulate {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Simulate",
        "Mimic(neutral)",
        "Pastiche {Kaplan, Majortest, Manhattan}",
    ],
    "Inspiring Fear Or Respect": [
        "Awe",
        "Formidable",
        "Redoubtable {Magoosh, Princeton}",
        "edifying",
    ],
    "Irritable": [
        "Cantankerous {Majortest}",
        "Chagrin {Barron, Magoosh}",
        "Choleric {Magoosh, Majortest}",
        "Churlish {Magoosh}",
        "Curmudgeon {Kaplan, Magoosh, Majortest, Manhattan}",
        "Grouchy",
        "Gruff",
        "Irascible {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Testiness {Majortest}",
    ],
    "Inviolable": [
        "inviolable",
        "inviolate",
    ],
    "Admirable": [
        "estimable",
    ],
    "Mediator Or Lead(neutral)": [
        "Arbiter {Barron, Manhattan}",
        "Arbitrator {Majortest}",
        "Mediate",
        "Officiate(neutral)",
        "Preside(neutral)",
        "adjudicate",
    ],
    "Offensivel Or Lusty": [
        "Lascivious {Magoosh}",
        "Leer",
        "Lewd",
        "Lurid {Barron, Manhattan}",
        "Obscene",
        "Seamy",
        "Sordid {Barron, Magoosh, Princeton}",
        "Vulgar",
    ],
    "Respect": [
        "Commemorate",
        "Deference {Kaplan, Majortest, Manhattan}",
        "Exalt {Magoosh}",
        "Hallow {Majortest}",
        "Homage {Manhattan}",
        "Revere {Barron, Majortest}",
        "Venerate {Kaplan, Magoosh, Majortest, Manhattan}",
        "awesome",
        "deferential",
        "reverent",
    ],
    "Aspect": [
        "facet",
    ],
    "Secret(-)": [
        "Clandestine {Barron, Majortest}",
        "Covert {Barron, Majortest, Manhattan}",
        "Furtive {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Oblique {Kaplan, Majortest, Manhattan}",
        "Skulk",
        "Sly",
        "Stealth",
        "Surreptitious {Barron, Magoosh, Majortest}",
        "Overt(opposite) {Barron, Majortest}",
    ],
    "Take Away Forcibly": [
        "Appropriate {Magoosh, Manhattan, Princeton}",
        "Divest {Majortest, Manhattan}",
        "Expropriate",
        "Preempt {Magoosh, Manhattan}",
        "Usurp {Barron, Majortest}",
    ],
    "To Irritate Or Make Angry": [
        "Disgruntled {Barron}",
        "Exasperate {Magoosh}",
        "Grate {Majortest}",
        "Harangue {Magoosh, Majortest, Manhattan, Princeton}",
        "Heckle",
        "Indignation",
        "Infuriate",
        "Irksome {Majortest}",
        "Miffed",
        "Nag",
        "Nettle {Barron, Kaplan, Majortest, Manhattan}",
        "Peeve",
        "Pique {Barron, Majortest}",
        "Vex {Kaplan, Manhattan}",
        "badger",
        "harass",
        "irk",
        "nettlesome",
        "rankle",
        "vexatious",
    ],
    "To Think Deeply": [
        "Cogitate {Majortest}",
        "Contemplate",
        "Deliberate {Magoosh, Majortest}",
        "Introspect",
        "Mull",
        "Muse {Majortest}",
        "Pensive {Barron, Majortest}",
        "Ponder {Barron}",
        "Reflect",
        "Ruminate {Barron, Majortest, Manhattan}",
    ],
    "To think Deeply": [
        "anthropologist",
        "introspective",
    ],
}