# Auto-updated Jamboree list: list8

list8 = {
    "Acting Properly OR Misbehave(opposite)": [
        "Decorous {Kaplan, Magoosh, Manhattan}",
        "Demure {Magoosh}",
        "Prim",
        "Propriety {Barron, Kaplan, Manhattan}",
        "Seemly {Majortest}",
        "Execrable(Opposite) {Majortest}",
        "Flagrant(Opposite) {Barron, Majortest}",
        "Malfeasance(Opposite) {Magoosh}",
        "Unbecoming(Opposite)",
        "becoming",
        "indecorous",
    ],
    "Acting Properly OR Misbehave (Quick Move)": [
        "scurry",
        "start",
    ],
    "Chaos OR Confusion": [
        "Bedlam {Barron}",
        "Pandemonium {Barron}",
        "Tumultuous {Manhattan}",
        "Turbulence",
        "Turmoil",
        "Upheaval",
        "Welter {Manhattan}",
        "amuck",
        "frenzy",
        "melee",
    ],
    "State of Confusion": [
        "tumult",
    ],
    "Cheat OR deceive": [
        "Artful {Magoosh}",
        "Artifice {Barron, Magoosh, Majortest}",
        "Bilk {Kaplan, Majortest, Manhattan}",
        "Chicanery {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Crafty {Manhattan}",
        "Duplicity {Barron, Magoosh, Majortest, Manhattan}",
        "Fleece {Magoosh}",
        "Guile {Kaplan, Majortest, Manhattan}",
        "Gulled",
        "Hoodwink {Magoosh, Manhattan}",
        "Mislead",
        "Swindle",
        "Wily {Kaplan, Majortest, Manhattan}",
        "delude",
        "mulct",
        "subterfuge",
    ],
    "Criminals OR Law Breakers": [
        "Felon {Barron}",
        "Menace",
        "Miscreant {Magoosh}",
        "Rogue",
        "Scoundrel",
        "accomplice",
        "mercenary",
        "perpetrate",
        "quisling",
    ],
    "Disaster": [
        "Calamitous",
        "Cataclysm {Magoosh}",
        "Catastrophe",
        "Debacle {Barron, Majortest, Princeton}",
        "Coup(Opposite) {Barron}",
        "carnage",
        "catastrophic",
        "decimation",
        "fiasco",
        "havoc",
        "pestilence",
        "genocide",
    ],
    "Disease": [
        "malady",
    ],
    "Disregard": [
        "Discount",
        "Brush Aside",
    ],
    "Doubtful": [
        "Apprehensive {Majortest}",
        "Cynical {Majortest, Manhattan}",
        "Dubious {Barron, Majortest, Manhattan}",
        "Questionable",
        "Skeptical {Majortest}",
        "alleged",
    ],
    "Generous Supporter": [
        "Altruist",
        "Benefactor",
        "Beneficent {Manhattan}",
        "Benevolent {Barron, Majortest}",
        "Humane",
        "Magnanimous {Barron, Magoosh, Majortest, Manhattan}",
        "Munificent {Barron, Magoosh, Majortest, Manhattan}",
        "Patron {Majortest}",
        "Philanthropist",
        "altruism",
        "altruistic",
    ],
    "Generous": [
        "largess",
        "largesse",
        "unstinting",
    ],
    "Supporter": [
        "disciple",
    ],
    "Lack Of Respect": [
        "Audacious {Kaplan, Magoosh, Manhattan, Princeton}",
        "Brazen {Magoosh}",
        "Cheeky",
        "Effrontery {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Gall {Magoosh, Majortest}",
        "Impertinent {Magoosh}",
        "Impudent {Magoosh}",
        "Insolent {Magoosh}",
        "Nerve",
        "Presumptuous {Magoosh, Majortest, Manhattan, Princeton}",
        "Temerity {Barron, Magoosh}",
    ],
    "Lacking Foresight": [
        "improvident",
        "imprudent",
    ],
    "Overly Proud": [
        "Arrogant",
        "Bombastic {Kaplan, Manhattan, Princeton}",
        "Braggart {Majortest}",
        "Bravado",
        "Conceited",
        "Egotistical",
        "Haughty {Magoosh}",
        "Hubris {Magoosh, Princeton}",
        "Pompous",
        "Supercilious {Magoosh, Majortest}",
        "Swagger",
        "Vainglorious",
        "Unassuming(Opposite)",
        "Elitist",
        "egotist",
        "hauteur",
        "megalomania",
        "overweening",
        "pontificate",
        "vaunted",
    ],
    "Practically OR Possible": [
        "Conceivable",
        "Credible {Majortest}",
        "Feasible {Barron, Majortest, Manhattan}",
        "Plausible {Magoosh, Majortest, Manhattan}",
        "Pragmatic {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Utilitarian {Majortest}",
        "Verisimilar {Majortest, Manhattan}",
        "Viable {Barron, Manhattan}",
    ],
    "Pretense Of Morality(-)": [
        "Cant {Barron, Majortest}",
        "Hypocritical {Majortest}",
        "Prig",
        "Prude",
        "Sanctimonious {Barron, Magoosh, Majortest}",
    ],
    "Repeat": [
        "Recapitulate {Majortest, Manhattan}",
        "Rehash",
        "Reiterate",
        "recapitulation",
    ],
    "Represent": [
        "effigy",
    ],
    "Self Control": [
        "Abstemious {Barron, Kaplan, Majortest}",
        "Abstinence",
        "Celibacy",
        "Forbear",
        "Moderate",
        "Refrain",
        "Temperate {Majortest}",
        "abstain",
    ],
    "Self Control (Restraint)": [
        "temperance",
    ],
    "Shining": [
        "Effulgent",
        "Luminous {Kaplan, Manhattan, Princeton}",
        "Lustrous",
        "Scintillating {Magoosh}",
    ],
    "Risk/Opening": [
        "gambit",
    ],
    "Show-off(-)": [
        "Flamboyance",
        "Flaunt {Majortest}",
        "Grandiloquent {Magoosh, Manhattan}",
        "Grandiose",
        "Ostentatious {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Pretentious {Majortest, Manhattan}",
        "Panache(+)",
        "array",
        "flamboyant",
        "gaudy",
        "panache",
        "swagger",
    ],
    "Show-off(-) (Cheap)": [
        "tawdry",
    ],
    "Speak Less OR Few Words": [
        "Abbreviated",
        "Abridge {Manhattan}",
        "Brevity {Majortest}",
        "Condense",
        "Laconic {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Monosyllabic",
        "Pithy {Kaplan, Magoosh, Princeton}",
        "Reticent {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Succinct {Barron, Majortest, Princeton}",
        "Taciturn {Kaplan, Magoosh, Majortest, Manhattan}",
    ],
    "Talkative OR Lots Of Words": [
        "Garrulous {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Loquacious {Kaplan, Majortest, Manhattan, Princeton}",
        "Prolix {Magoosh, Manhattan, Princeton}",
        "Verbiage {Majortest}",
        "Verbose {Kaplan, Majortest, Manhattan}",
        "Voluble {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Long-winded",
    ],
    "Talkative OR Lots Of Words (Moralizing)": [
        "sententious",
    ],
    "To Give Control OR Responsibility": [
        "Delegate {Magoosh}",
        "Devolve {Magoosh}",
    ],
    "Without Deception": [
        "Dupe {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Artless {Barron, Magoosh, Majortest, Manhattan}",
        "Credence OR Credible {Magoosh}",
        "Credulous {Kaplan, Majortest, Manhattan, Princeton}",
        "Guileless {Magoosh, Majortest}",
        "Gullible {Barron, Kaplan, Majortest}",
        "Naive Or Naivete",
        "Ingenuous {Kaplan, Magoosh, Manhattan, Princeton}",
        "aboveboard",
        "artlessness",
    ],
    "Without Deception (Truthful)": [
        "veracious",
        "verisimilitude",
    ],
}