# Auto-updated Jamboree list: list2

list2 = {
    "Bitter feelings OR Ill will": [
        "Malevolence",
        "Malice",
        "Rancor {Majortest}",
        "Vicious",
        "Virulent {Barron, Majortest, Manhattan, Princeton}",
        "acrimony",
        "enmity",
        "hostile",
    ],
    "Bitter feelings OR Ill will (Corrupt)": [
        "venality",
    ],
    "Bitter feelings OR Ill will (Joy in Pain)": [
        "schadenfreude",
    ],
    "Cautions OR Careful OR Risky(Opposite)": [
        "Chary {Magoosh, Majortest, Princeton}",
        "Circumspect {Kaplan, Majortest, Manhattan}",
        "Gingerly",
        "Heedful",
        "Leery {Kaplan, Magoosh, Manhattan}",
        "Prudent {Barron, Majortest, Manhattan}",
        "Wary {Barron, Majortest, Manhattan}",
        "Daredevil(Opposite)",
        "Folly(Opposite)",
        "Foolhardy(Opposite) {Magoosh, Majortest}",
        "Rash(Opposite) {Barron, Magoosh}",
        "Reckless(Opposite)",
        "Caveat",
        "adjective",
    ],
    "Coming Together": [
        "Coalesce {Kaplan, Magoosh, Majortest, Manhattan}",
        "Rally",
        "propinquity",
        "proximity",
    ],
    "Complain(Low Degree)": [
        "Captious {Princeton}",
        "Carping {Magoosh, Majortest}",
        "Grouse {Manhattan, Princeton}",
        "Querulous {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "bemoan",
        "inveigh",
        "rail",
        "screed",
    ],
    "Danger": [
        "Jeopardy",
        "Pitfall",
        "Precarious {Magoosh, Majortest, Manhattan}",
        "Snare",
        "jeopardize",
    ],
    "Abundance": [
        "flush",
    ],
    "Manage": [
        "eke",
    ],
    "Disapprove OR Scold": [
        "Assail {Kaplan, Magoosh, Manhattan}",
        "Berate {Majortest}",
        "Castigate {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Decry {Magoosh}",
        "Denounce {Majortest}",
        "Denunciation",
        "Diatribe {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Epithet {Barron, Majortest}",
        "Excoriate {Barron, Magoosh, Princeton}",
        "Fulminate {Majortest, Manhattan, Princeton}",
        "Invective {Barron, Kaplan, Magoosh, Manhattan}",
        "Lambaste {Magoosh, Majortest}",
        "Rant {Majortest}",
        "Rile {Magoosh}",
        "Revile {Barron}",
        "Tirade {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Upbraid {Kaplan, Magoosh, Majortest, Manhattan}",
        "Vituperative",
        "declaim",
        "deprecate",
        "objurgate",
        "pillory",
        "vituperate",
    ],
    "Emphasize": [
        "Accentuate",
        "Foreground",
        "Underscore {Magoosh, Majortest, Manhattan}",
    ],
    "Hate": [
        "Abhor {Barron, Majortest, Manhattan}",
        "Animosity {Magoosh, Majortest}",
        "Antipathy {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Aversion {Barron, Majortest}",
        "Despicable",
        "Detest",
        "Loathe {Barron}",
        "Odious {Majortest, Princeton}",
        "Repel",
        "Repugnant {Barron}",
        "Repulsion",
        "misanthrope",
        "misogynist",
    ],
    "Hate/Evil": [
        "malevolent",
    ],
    "Hateful": [
        "invidious",
    ],
    "Humiliate": [
        "demean",
    ],
    "Minor Scolding OR Warning": [
        "Admonish {Barron, Magoosh, Manhattan}",
        "Censure {Magoosh, Majortest, Manhattan, Princeton}",
        "Chastise {Magoosh}",
        "Chide",
        "Rebuke {Barron, Magoosh}",
        "Reprimand {Barron}",
        "Reproach {Barron, Magoosh, Manhattan}",
        "Reprove",
        "admonitory",
    ],
    "Mock OR Disrespect(-)": [
        "Abase {Kaplan, Manhattan}",
        "Belittle {Barron, Magoosh, Majortest}",
        "Condescend {Majortest}",
        "Contempt",
        "Denigrate {Magoosh, Majortest, Manhattan}",
        "Deride {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Disdain {Barron, Majortest}",
        "Disparage {Barron, Majortest, Manhattan, Princeton}",
        "Jeer",
        "Lampon",
        "Patronize {Magoosh, Majortest}",
        "Sarcastic",
        "Sardonic {Kaplan, Magoosh, Majortest, Manhattan}",
        "Satire {Princeton}",
        "Scoff {Barron}",
        "Scorn",
        "Sneer",
        "Snicker",
        "Snide {Magoosh}",
        "Spurn {Magoosh}",
        "Taunt {Majortest}",
        "Banter(+)",
        "Raillery(+)",
        "contemptuous",
        "derisive",
        "derogative",
    ],
    "Old Fashioned OR Outdated": [
        "Antediluvian {Majortest}",
        "Antiquated {Barron, Magoosh, Majortest}",
        "Archaic {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Dated",
        "Obsolete {Majortest, Manhattan}",
        "Outmode",
        "Quaint {Majortest}",
        "hoary",
        "obsolescence",
        "tradition",
    ],
    "Praise": [
        "Acclaim",
        "Accolade {Magoosh, Majortest, Princeton}",
        "Applaud",
        "Approbation {Kaplan, Majortest, Manhattan, Princeton}",
        "Commendable {Magoosh}",
        "Eulogy {Kaplan, Majortest, Manhattan, Princeton}",
        "Exalt {Magoosh}",
        "Extol {Barron, Majortest}",
        "Glorify",
        "Hail {Magoosh}",
        "Laud {Kaplan, Majortest, Princeton}",
        "Lionize {Kaplan, Magoosh, Manhattan}",
        "Plaudit {Majortest}",
        "Encomiastic",
        "approbatory",
        "encomium",
        "laudable",
        "panegyric",
        "repute",
        "venerable",
        "creditable",
    ],
    "Praise (Tact)": [
        "tact",
    ],
    "Rebellious OR Unconventional": [
        "Dissident {Majortest}",
        "Heresy {Barron, Majortest}",
        "Heretical {Princeton}",
        "Heterodox {Majortest, Princeton}",
        "Iconoclast {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Insurgent {Majortest}",
        "Insurrection {Kaplan, Manhattan}",
        "Maverick {Magoosh, Majortest, Manhattan, Princeton}",
        "Nonconformist",
        "Radical",
        "Reactionary(Opposite)",
        "Renegade",
        "Revolutionary",
        "Subversive {Magoosh, Majortest}",
        "Conservative(Opposite)",
        "Conventional(Opposite) {Majortest}",
        "Orthodox(Opposite) {Majortest, Manhattan}",
        "Hidebound {Majortest}",
        "iconoclastic",
        "heretic",
        "rakish",
    ],
    "Rule OR Principle": [
        "Axioms",
        "Canons",
        "Dictum {Kaplan, Manhattan}",
        "Doctrine",
        "Dogmas",
        "Mandate {Barron}",
        "Tenets",
        "Ideology",
        "aphorism",
        "aphoristic",
        "apothegm",
        "cardinal",
        "maxim",
    ],
    "Rule OR Principle (Territory)": [
        "realm",
        "site",
    ],
    "Rule OR Principle (Logic)": [
        "premise",
        "shibboleth",
    ],
    "Rule OR Principle (Moral)": [
        "ethics",
    ],
    "Self-Satisfaction(-)": [
        "Gloat",
        "Smirk",
        "Smug {Magoosh}",
        "Bask(+)",
        "Complacent {Barron, Magoosh, Majortest, Manhattan}",
    ],
    "Similarity": [
        "Analogy",
        "Antithetical(Opposite) {Magoosh, Manhattan}",
        "atavism",
    ],
    "Humility": [
        "humility",
    ],
    "Time Related Words": [
        "Anachronism {Kaplan, Magoosh, Manhattan, Princeton}",
        "Chronicle",
        "Chronological {Manhattan}",
        "decade",
        "elapse",
    ],
    "Time Related Words (Spirit)": [
        "zeitgeist",
    ],
    "Related (Descendants)": [
        "progeny",
        "scion",
    ],
    "To Defeat OR Surrender": [
        "Drub",
        "Pulverize",
        "Rout",
        "Subjugate {Barron}",
        "Vanquish {Magoosh}",
        "Capitulate {Barron, Magoosh, Majortest}",
    ],
    "To Defeat OR Surrender (Opposite)": [
        "repulse",
    ],
    "Troubled": [
        "Beset",
        "Beleaguered",
        "Plagued",
        "disaffected",
        "harried",
    ],
    "Trend": [
        "trend",
    ],
    "Troublemaker": [
        "firebrand",
    ],
}