# Auto-updated Jamboree list: list6

list6 = {
    "Accept OR Agree OR Given In": [
        "Accede {Manhattan}",
        "Acquiesce {Barron, Majortest}",
        "Amenable {Magoosh, Princeton}",
        "Assent",
        "Compliant {Majortest, Manhattan}",
        "Comply",
        "Concede {Magoosh, Manhattan}",
        "Concur {Barron, Manhattan}",
        "Pliant",
        "Relent",
        "Succumb {Barron}",
        "Yield",
        "Docile(Easily Control)",
        "Malleable(Easily Control)",
    ],
    "Break a Rule": [
        "Breach",
        "Flout {Barron, Majortest, Manhattan, Princeton}",
        "Transgress {Majortest}",
        "Abide(Opposite)",
        "Adhere(Opposite) {Manhattan}",
        "Infraction {Barron}",
    ],
    "Cancel OR Take Back": [
        "Annul {Manhattan}",
        "Disavow",
        "Gainsay {Magoosh, Majortest, Manhattan, Princeton}",
        "Null",
        "Recant {Barron, Majortest, Manhattan, Princeton}",
        "Renege {Magoosh, Majortest, Princeton}",
        "Repeal",
        "Repudiate {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Rescind {Magoosh, Majortest, Manhattan, Princeton}",
        "Retract {Magoosh}",
        "Revoke",
        "Void",
        "abrogate",
        "countermand",
        "invalidate",
    ],
    "Cancel OR Take Back (Withdraw)": [
        "retracted",
        "revoked",
    ],
    "Clothing": [
        "Sartorial {Magoosh}",
        "Raiment {Barron}",
        "pall",
    ],
    "Flowing": [
        "flux",
    ],
    "Co-Existing": [
        "Contemporary {Majortest}",
        "Simultaneous {Manhattan}",
        "conjugal",
        "connubial",
        "coterminous",
    ],
    "Existing": [
        "extant",
    ],
    "Determined(+)": [
        "Dogged",
        "Endure",
        "Immutable {Magoosh, Majortest, Manhattan, Princeton}",
        "Indefatigable {Manhattan, Princeton}",
        "Persevere {Barron}",
        "Persistence",
        "Resolute",
        "Steadfast {Magoosh}",
        "Tenacious {Barron, Magoosh, Majortest}",
        "aspirant",
        "aspire",
        "obsess",
        "staunch",
        "volition",
    ],
    "Derived": [
        "derive",
        "derived",
    ],
    "Energizing": [
        "Galvanizing",
        "Invigorating",
        "Revitalizing",
        "Rousing",
    ],
    "Begin": [
        "originate",
    ],
    "Extra Hence Unnecessary": [
        "Extraneous {Barron, Majortest, Manhattan}",
        "Redundant {Majortest}",
        "Superfluous {Barron, Magoosh, Princeton}",
        "perquisite",
    ],
    "Famous Person": [
        "Eminent {Barron, Magoosh, Manhattan}",
        "Luminary {Majortest}",
        "Pre-Eminent",
        "Stature",
        "arriviste",
        "illustrious",
    ],
    "Famous Person (Status)": [
        "prestigious",
    ],
    "Facial Expression": [
        "grimace",
    ],
    "Greed": [
        "Avarice {Barron, Magoosh, Manhattan, Princeton}",
        "Covetous",
        "Cupidity {Barron, Kaplan, Magoosh, Manhattan}",
        "Glutton(Food)",
        "Rapacious",
        "Ravenous {Magoosh}",
        "Voracious {Barron, Magoosh, Majortest, Princeton}",
        "Mercenary(Materialistic)",
        "avaricious",
        "covet",
        "materialism",
    ],
    "Overly Noise(-)": [
        "Cacophony {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Clamor {Majortest, Manhattan}",
        "Clangor",
        "Din {Manhattan}",
        "Discordant {Manhattan, Princeton}",
        "Raucous {Barron, Majortest}",
        "Strident {Barron, Majortest}",
        "Uproar",
        "Vociferous {Magoosh, Majortest, Manhattan}",
        "Boisterous(Loud and Excited)",
        "Inaudible(Opposite)",
        "Obstreperous {Magoosh, Majortest, Princeton}",
        "stentorian",
    ],
    "Planned OR Spontaneous (Opposite)": [
        "Calculated",
        "Deliberate {Magoosh, Majortest}",
        "Forethought",
        "Intentional",
        "Premeditated",
        "Studied",
        "Extemporaneous(Opposite) {Manhattan, Princeton}",
        "Impetuous(Opposite) {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Impromptu(Opposite) {Barron, Majortest}",
        "Improvise(Opposite)",
        "Offhand(Opposite) {Manhattan}",
        "preemptive",
        "spontaneous",
    ],
    "Bad Smell (Opposite - Pleasant)": [
        "redolent",
    ],
    "Pleasant Sounding": [
        "Euphony {Kaplan, Majortest, Manhattan}",
        "Melodious",
        "Mellifluous {Magoosh}",
        "dulcet",
    ],
    "Legally Binding": [
        "fiat",
    ],
    "Profitable": [
        "Remunerative",
        "Lucrative {Barron}",
        "pecuniary",
        "remuneration",
        "defray",
    ],
    "Severe": [
        "Acute {Barron}",
        "Austere {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "decapitate",
        "flay",
    ],
    "Severe (Weather)": [
        "inclement",
    ],
    "Stubborn(-)": [
        "Adamant {Barron, Magoosh, Majortest}",
        "Defiant",
        "Incorrigible {Magoosh}",
        "Intractable {Kaplan, Manhattan, Princeton}",
        "Intransigent {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Obdurate {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Obstinate {Kaplan, Magoosh, Manhattan, Princeton}",
        "Pertinacious",
        "Perverse {Barron}",
        "Recalcitrant {Manhattan, Princeton}",
        "Refractory {Magoosh, Manhattan}",
        "Willful {Majortest}",
        "ossify",
        "uncompromising",
    ],
    "Supporter OR Enemy(Opposite)": [
        "Advocate {Barron, Kaplan, Majortest, Manhattan}",
        "Ally",
        "Champion {Magoosh}",
        "Endorse {Majortest}",
        "Espouse {Magoosh, Majortest}",
        "Lobbyist {Majortest}",
        "Protagonist {Majortest}",
        "Tout {Magoosh, Princeton}",
        "Proponent {Magoosh}",
        "Adversary(Opposite) {Barron}",
        "Antagonist(Opposite)",
        "Detractor(Opposite)",
        "Foe(Opposite)",
        "Impugn(Opposite) {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Inimical(Opposite) {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Nemesis(Opposite)",
        "Opponent(Opposite)",
        "adherent",
    ],
    "To Approach Something": [
        "Accost(-)",
        "Broach(+)",
        "access",
        "accost",
        "jostle",
    ],
    "To Make Up OR Create": [
        "Concoct {Barron}",
        "Devise",
        "Formulate",
        "Conjure",
        "arrogate",
        "contrive",
        "machinate",
        "deploy",
    ],
    "To Make Up OR Create (Seize)": [
        "wrest",
    ],
    "To Make Up OR Create (Break Out)": [
        "recrudesce",
        "resurgent",
    ],
    "To Object OR Resist": [
        "Defy",
        "Demur {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Dissent {Barron, Manhattan}",
        "Take Issue With",
        "adverse",
        "buck",
    ],
    "To Prove False OR To Disprove": [
        "Belie {Magoosh, Majortest, Manhattan}",
        "Debunk {Magoosh, Manhattan}",
        "Discredit {Manhattan}",
        "Expostulate {Majortest}",
        "Rebut",
        "Refute {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Remonstrate {Magoosh, Princeton}",
    ],
    "Urgent": [
        "Exigent {Kaplan, Manhattan, Princeton}",
        "Pressing",
        "requisite",
    ],
    "Target": [
        "quarry",
    ],
}