# Auto-updated Jamboree list: list5

list5 = {
    "Cannot be Defeated": [
        "Impervious {Kaplan, Magoosh, Manhattan}",
        "Indomitable",
        "Invincible",
        "impregnable",
    ],
    "Combine": [
        "Amalgamate {Kaplan, Majortest, Manhattan, Princeton}",
        "Coalition",
        "Meld",
        "Synthesis {Princeton}",
        "amalgam",
        "conflate",
    ],
    "Excess": [
        "Abound {Barron}",
        "Barrage {Majortest}",
        "Bounteous",
        "Copious {Barron, Magoosh, Manhattan}",
        "Glut {Magoosh}",
        "Inundate {Barron, Kaplan, Magoosh, Manhattan}",
        "Myriad {Barron, Magoosh, Majortest}",
        "Plethora {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Profuse {Barron, Magoosh, Manhattan, Princeton}",
        "Prolific {Barron, Magoosh, Majortest, Princeton}",
        "Steeped {Manhattan}",
        "Surfeit {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Surge {Barron}",
        "Teeming",
        "cornucopia",
        "flush",
        "profusion",
        "spate",
        "deluge",
    ],
    "Excess (Growth)": [
        "lush",
    ],
    "Excessive Patriotism (-)": [
        "Chauvinism {Magoosh, Manhattan}",
        "Fanatic",
        "Jingoism {Kaplan, Magoosh, Manhattan}",
        "Zealot {Kaplan, Majortest}",
        "Idealogue",
    ],
    "Explain Too Much": [
        "Belabor {Majortest}",
        "Understatement(Opposite)",
        "ascribe",
    ],
    "Explain Too Much OR Critical Analysis": [
        "exegesis",
    ],
    "Increase": [
        "Accretion {Kaplan, Majortest, Manhattan}",
        "Aggrandize {Kaplan, Manhattan, Princeton}",
        "Augment {Barron, Magoosh, Majortest, Manhattan}",
        "Ballon",
        "Dilate {Kaplan, Manhattan}",
        "Enhance {Barron, Majortest, Manhattan}",
        "Mounting",
        "Proliferate {Kaplan, Majortest, Manhattan, Princeton}",
        "Wax {Magoosh, Majortest}",
        "compound",
        "cumulative",
    ],
    "Sinecure": [
        "sinecure",
    ],
    "Lessen In Intensity": [
        "Abate {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Ebb",
        "Recede",
        "Subside {Manhattan}",
        "palliate",
        "propitiate",
        "tempered",
    ],
    "Lucky OR Unlucky": [
        "Fortuitous {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Opportune",
        "Propitious {Barron, Magoosh, Manhattan}",
        "Serendipity {Magoosh, Majortest}",
        "Despair(Opposite)",
        "Hapless(Opposite) {Barron, Kaplan, Majortest, Manhattan}",
        "Wretched(Opposite)",
        "auspicious",
        "felicitous",
        "infelicitous",
    ],
    "Lucky OR Unlucky (Ruined)": [
        "pyrrhic",
    ],
    "Lucky OR Unlucky (Inevitable)": [
        "ineluctable",
    ],
    "Nervous OR Restless": [
        "Restive {Kaplan, Magoosh, Manhattan}",
        "Skittish {Manhattan}",
        "neurotic",
        "phobia",
        "quail",
        "unnerve",
        "wince",
    ],
    "Pursue Relentlessly": [
        "hound",
        "dog",
    ],
    "Pain OR Suffering": [
        "Adversity {Majortest}",
        "Afflictions",
        "Mishap",
        "Ordeals",
        "Trials",
        "Tribulation {Magoosh}",
        "afflict",
        "excruciating",
    ],
    "Poor": [
        "Bankrupt",
        "Destitute {Magoosh}",
        "Impecunious {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Impoverished {Majortest}",
        "Indigent {Barron, Magoosh, Majortest}",
        "Insolvent {Magoosh}",
        "Penury {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Solvent(Opposite) {Princeton}",
        "privation",
    ],
    "Color": [
        "tinge",
    ],
    "Poor/Beggar": [
        "mendicant",
    ],
    "Sponsor": [
        "impresario",
    ],
    "Reduce OR Restrict": [
        "Constrict {Manhattan}",
        "Contract",
        "Curtail {Barron, Majortest}",
        "Dwindle",
        "Flag {Kaplan, Majortest, Manhattan, Princeton}",
        "Wane {Barron, Majortest}",
    ],
    "Rude (No Restraint)": [
        "wanton",
    ],
    "Relevant": [
        "Apposite {Majortest, Manhattan}",
        "Apropos",
        "Germane {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Pertinent {Barron, Magoosh, Majortest}",
        "expedient",
    ],
    "Irrelevant": [
        "irrelevant",
    ],
    "Remembering The Past": [
        "Evocative",
        "Hindsight",
        "Nostalgia {Barron, Majortest}",
        "Reminiscence",
        "Retrospect {Barron}",
        "Wistful {Barron, Majortest}",
    ],
    "Routine Behavior": [
        "Obtain {Magoosh}",
        "Wont",
        "demeanor",
        "mien",
        "trait",
    ],
    "Shortage OR Lack of": [
        "Dearth {Barron, Princeton}",
        "Deficit",
        "Paucity {Barron, Majortest, Manhattan}",
        "Vacuous {Magoosh, Majortest}",
        "malnutrition",
    ],
    "Spend Too Much OR Waste(-)": [
        "Prodigal {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Profligate {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Spendthrift {Magoosh, Princeton}",
        "Squander {Magoosh, Princeton}",
        "Extravagance",
        "Lavish {Kaplan, Majortest, Manhattan}",
    ],
    "Used To (Tolerate)": [
        "tolerate",
    ],
    "Sure OR Certain OR Conditional(Opposite)": [
        "Absolute",
        "Categorical",
        "Certitude {Majortest}",
        "Conviction",
        "Emphatic",
        "Incontrovertible {Barron, Magoosh}",
        "Unqualified",
        "Contingent(Opposite) {Magoosh}",
        "Provisional(Opposite) {Magoosh}",
        "Qualify(Opposite) {Magoosh, Princeton}",
        "Tentative(Opposite) {Majortest}",
        "unmitigated",
    ],
    "Unclear In Meaning": [
        "Ambivalent {Magoosh, Manhattan}",
        "Ambiguous {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Equivocal {Magoosh, Majortest}",
        "denote",
        "equivocate",
        "evasive",
        "garbled",
        "inkling",
        "opaque",
        "prevaricate",
    ],
    "Unwilling To Spend(-)": [
        "Closefisted",
        "Miserly",
        "Niggardly {Majortest}",
        "Parsimonious {Barron, Magoosh, Majortest, Princeton}",
        "Skinflint",
        "Stingy {Manhattan}",
        "Stint {Manhattan}",
        "Tightfisted",
        "Thrift",
        "Frugal {Barron, Magoosh, Majortest, Manhattan}",
        "Husbandry",
        "Economical OR Economy {Magoosh}",
        "miser",
        "penurious",
        "thrifty",
    ],
    "Very High Price(-)": [
        "Exorbitant {Magoosh}",
        "Gouging",
        "Prohibitive {Majortest, Manhattan}",
    ],
    "Very High Price(-) (Utmost)": [
        "ultimate",
    ],
    "Very Less(-)": [
        "Exiguous",
        "Meager {Majortest}",
        "Puny {Barron}",
        "Scanty",
        "Skimpy",
        "Spare",
        "Sparse {Majortest, Princeton}",
        "modicum",
        "pittance",
        "smattering",
    ],
    "Very Less (Lowest Point)": [
        "nadir",
    ],
    "Wealthy": [
        "Opulent {Majortest}",
        "Affluent {Barron, Magoosh}",
        "afford",
        "opulence",
        "parvenu",
    ],
    "Power/Authority": [
        "jurisdiction",
    ],
}