# Auto-updated Jamboree list: list13

list13 = {
    "Activate OR Speed Up": [
        "Catalyst {Kaplan, Manhattan, Princeton}",
        "Engender {Kaplan, Magoosh, Majortest, Manhattan}",
        "Expedite {Barron, Majortest}",
        "Facilitate {Manhattan}",
        "Kindle {Kaplan, Majortest, Manhattan}",
        "Precipitate {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Prod",
        "Prompt",
        "Propel",
        "Spur",
        "Stimulate",
        "celerity",
        "dispatch",
        "motivate",
        "scurry",
        "whet",
        "initiate",
    ],
    "Attractive OR Decorative": [
        "Adorn",
        "Embellish {Barron, Kaplan, Magoosh, Manhattan}",
        "Florid {Kaplan, Manhattan}",
        "Garnish",
        "Ornate {Magoosh, Majortest}",
        "Resplendent {Majortest}",
        "Spectacular",
        "aesthete",
    ],
    "Attractive (Opposite)": [
        "unprepossessing",
    ],
    "Attractive OR Decorative (Sexual)": [
        "sultry",
    ],
    "Ban": [
        "Interdict",
        "Sanction {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Veto",
        "bowdlerize",
        "inhibition",
        "prohibition",
        "proscribe",
        "restrictive",
    ],
    "Blameworthy OR Guilty": [
        "Culpable {Barron, Princeton}",
        "Reprehensible {Barron, Majortest}",
        "complicit",
        "complicity",
        "culpability",
    ],
    "Wealthy (Superior Quality)": [
        "sumptuous",
    ],
    "Can’t Decide OR Fickle": [
        "Arbitrary {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Capricious {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Erratic {Kaplan, Magoosh, Majortest, Manhattan}",
        "Inconsistent",
        "Irresolute {Magoosh, Manhattan}",
        "Mercurial {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Oscillate {Manhattan}",
        "Sway",
        "Temperamental",
        "Vacillate {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Volatile {Kaplan, Majortest, Manhattan, Princeton}",
        "Waffle {Majortest, Princeton}",
        "Waver {Kaplan, Magoosh, Princeton}",
        "Whimsical {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
    ],
    "Careless OR Dirty": [
        "Disheveled {Barron}",
        "Rumpled",
        "Shabby",
        "Shoddy",
        "Sloppy",
        "Slovenly {Barron}",
        "Unkempt {Barron}",
        "slapdash",
    ],
    "Confirm OR Support": [
        "Affirm",
        "Clinch {Manhattan}",
        "Corroborate {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Endorse {Majortest}",
        "Ratify {Majortest}",
        "Substantiate {Barron, Majortest, Manhattan}",
        "Testify",
        "Validate",
        "Unfounded (Opposite)",
    ],
    "Dead End": [
        "Impasse {Kaplan, Manhattan}",
        "Stalemate",
    ],
    "Plead (Demand)": [
        "stipulate",
    ],
    "End": [
        "extinct",
    ],
    "Disrespecting Sacred Things": [
        "Blasphemy {Majortest}",
        "Desecrate {Magoosh, Majortest}",
        "Impious {Barron, Kaplan, Majortest, Manhattan}",
        "Profane {Majortest}",
        "Sacrilege",
        "Consecrate (Opposite) {Magoosh, Majortest}",
        "Sacrosanct (Opposite) {Kaplan, Majortest, Manhattan}",
        "Anoint (Opposite) {Manhattan}",
    ],
    "Free From Blame": [
        "Absolve",
        "Acquit",
        "Exculpate {Kaplan, Majortest, Manhattan, Princeton}",
        "Exonerate {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Vindicate {Barron, Magoosh, Majortest}",
    ],
    "Harmless OR Kind": [
        "Benign {Magoosh, Majortest, Manhattan}",
        "Innocuous {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "salubrious",
    ],
    "Name Origin": [
        "eponym",
    ],
    "Helpful": [
        "Officious (-)",
        "Solicitous (+)",
        "salvation",
    ],
    "Helpful (Concerned)": [
        "solicitous",
        "solicitude",
        "tender",
    ],
    "Left Over": [
        "Remnant",
        "Residual",
        "Trace",
        "Vestige {Barron, Kaplan, Manhattan}",
        "Modicum (Neutral)",
        "debris",
    ],
    "Legal Terms": [
        "plaintiff",
    ],
    "Takeover": [
        "junta",
    ],
    "Mutual Agreement": [
        "Consensus {Majortest}",
        "Unanimous",
    ],
    "Not Through OR Superficially": [
        "Cursory {Barron}",
        "Perfunctory {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Summarily",
        "superficial",
    ],
    "Physically Strong": [
        "Robust {Magoosh, Majortest}",
        "Rugged",
        "Sturdy",
        "Vigorous",
        "asset",
        "firm",
    ],
    "Physically Strong (Energy)": [
        "virile",
    ],
    "Physically Strong (Tight)": [
        "taut",
    ],
    "Physically Strong (Loyal)": [
        "stalwart",
    ],
    "Physical Condition": [
        "jaundice",
    ],
    "Physically Large": [
        "corpulent",
    ],
    "Punish": [
        "Condemn",
        "Convict",
        "Immure {Magoosh}",
        "Incarcerate",
        "Sentence",
        "Amnesty (Opposite) {Barron}",
        "Condone (Opposite) {Barron, Kaplan, Majortest, Manhattan}",
        "Reprieve (Opposite) {Majortest}",
        "penance",
    ],
    "Restrict OR Stop OR Prevent": [
        "Check {Magoosh}",
        "Deter {Barron, Magoosh, Majortest}",
        "Foil",
        "Forestall {Kaplan, Manhattan}",
        "Frustrate {Barron, Magoosh}",
        "Hinder {Majortest}",
        "Impede OR Impediment {Barron, Magoosh, Manhattan}",
        "Inhibit",
        "Obstruct",
        "Preclude {Barron, Magoosh, Majortest}",
        "Retard",
        "Stymie {Barron, Magoosh, Manhattan, Princeton}",
        "Thwart {Barron, Magoosh, Majortest}",
        "Occlude {Kaplan, Manhattan, Princeton}",
        "Stanch {Majortest}",
        "Preempt {Magoosh, Manhattan}",
        "hedge",
    ],
    "Simple OR Plain OR Boring": [
        "Ascetic {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Austere {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Bland",
        "Drab",
        "Insipid {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Prosaic {Magoosh, Majortest, Manhattan, Princeton}",
        "Stark {Manhattan}",
        "Vapid {Barron, Majortest}",
        "jejune",
        "muted",
        "nondescript",
        "plodding",
        "shallow",
    ],
    "Simple OR Plain OR Boring (Strict)": [
        "spartan",
    ],
    "To Blame OR Accuse OR Charge": [
        "Allege OR Allegation",
        "Implicate {Magoosh}",
        "Impute {Magoosh, Manhattan}",
        "Incriminate",
        "Indict {Barron, Magoosh}",
        "Recriminate (Neutral)",
    ],
    "Unsteady Walk OR Hesitate": [
        "Falter {Barron, Majortest}",
        "Flounder {Magoosh}",
        "Founder",
        "Fumble",
        "To Run Around",
        "Tottering",
        "Wobbly",
        "hobble",
        "fluctuate",
    ],
    "Unsteady Walk OR Hesitate (Spring Back)": [
        "recoil",
    ],
    "Unsteady Walk OR Hesitate (Unlikely)": [
        "unpropitious",
    ],
    "Unsteady Walk OR Hesitate (Novel)": [
        "unprecedented",
    ],
    "Without Real Power": [
        "Figurehead {Majortest}",
        "Nominal {Barron, Kaplan, Manhattan}",
        "Titular",
        "automaton",
        "nonentity",
    ],
    "Illegal Use of Power": [
        "graft",
    ],
}