# Auto-updated Jamboree list: list10

list10 = {
    "Accuse Or Defame": [
        "Aspersion",
        "Calumny {Barron, Kaplan, Magoosh, Manhattan}",
        "Defame",
        "Libel {Barron}",
        "Malign {Majortest}",
        "Obloquy {Barron}",
        "Opprobrium {Barron, Kaplan, Manhattan, Princeton}",
        "Slander",
        "Slur",
        "Stigmatization",
        "Vilify {Magoosh, Princeton}",
        "villify",
        "degrade",
    ],
    "Alert": [
        "Vigilant {Barron, Princeton}",
        "Disarm(opposite) {Majortest}",
        "Inattentive",
        "vigil",
    ],
    "Attract Or Fascinate": [
        "Arresting {Majortest, Princeton}",
        "Captivate",
        "Delectable",
        "Enamored",
        "Enthrall {Magoosh}",
        "Infatuate",
        "Mesmerize {Magoosh}",
        "Rapture",
        "Spellbinding",
        "Ennui(opposite) {Barron, Princeton}",
        "amorous",
        "enamor",
    ],
    "Beginner Or Inexperienced": [
        "Apprentice",
        "Dilettante {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Novel {Majortest, Manhattan}",
        "Novice {Majortest}",
        "Rookie",
        "dilletante",
        "just beginning",
        "naive",
        "tyro",
    ],
    "Brave": [
        "Audacious {Kaplan, Magoosh, Manhattan, Princeton}",
        "Chivalry",
        "Dauntless",
        "Gallant",
        "Intrepid {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Pluck {Majortest, Princeton}",
        "Undaunted",
        "Valiant",
        "Valor {Barron}",
        "brash",
        "doughty",
        "mettlesome",
        "plucky",
    ],
    "Contradict Itself": [
        "Irony Or Ironic",
        "Paradox {Barron, Kaplan, Majortest, Manhattan}",
        "antithesis",
    ],
    "Counter Attack": [
        "Retaliate",
        "Reprisal {Magoosh}",
    ],
    "Cure All": [
        "Panacea {Barron, Majortest}",
        "Elixir",
        "anodyne",
    ],
    "Cure All (Therapy)": [
        "therapy",
    ],
    "Delay Or Postpone": [
        "Adjourn",
        "Defer",
        "Protract",
        "Procrastinate {Barron, Majortest}",
        "belated",
    ],
    "Disrepute Or Bad Reputation": [
        "Ignominy {Majortest}",
        "Infamy",
        "Nefarious {Barron, Majortest}",
        "Notorious",
        "ignoble",
        "ignominious",
        "infamous",
    ],
    "Embarrass": [
        "Abash",
        "Discomfit",
        "Mortify",
    ],
    "Fake Or False Or Doubtful": [
        "Apocryphal {Kaplan, Magoosh, Majortest, Manhattan}",
        "Dubious {Barron, Majortest, Manhattan}",
        "Erroneous {Manhattan}",
        "Ersatz {Kaplan, Magoosh, Manhattan}",
        "Fabricate {Barron}",
        "Fallacious {Barron, Magoosh, Majortest, Manhattan}",
        "Illicit {Magoosh}",
        "Phony {Manhattan}",
        "Sham",
        "Sophistry {Barron}",
        "Specious {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Spurious {Barron, Magoosh, Majortest, Princeton}",
        "Propaganda",
        "askance",
        "bogus",
        "charlatan",
        "hoax",
    ],
    "Fake Or False Or Doubtful (Imitation)": [
        "travesty",
    ],
    "Falsehood": [
        "Mendacity {Magoosh, Princeton}",
        "Perjury {Majortest}",
        "Prevarication",
        "Veracity(opposite) {Kaplan, Majortest, Manhattan, Princeton}",
        "canard",
        "mendacious",
    ],
    "Fearful Or Lacking Courage": [
        "Cower {Majortest}",
        "Craven {Kaplan, Magoosh, Manhattan}",
        "Cringe {Majortest}",
        "Daunt {Manhattan}",
        "Flinch",
        "Petrify {Majortest}",
        "Pusillanimous {Kaplan, Majortest, Manhattan, Princeton}",
        "Shrink",
        "Trepidation {Majortest}",
        "appalled",
        "apprehension",
    ],
    "Abusive Language": [
        "vituperation",
    ],
    "Specialized Language": [
        "jargon",
    ],
    "Fluent Or Clear": [
        "Articulate {Kaplan, Majortest, Manhattan}",
        "Coherent",
        "Eloquent {Kaplan, Majortest, Manhattan, Princeton}",
        "Enunciate {Barron}",
        "Glib(smooth Talker)",
        "Labored(opposite)",
        "Ineffable(opposite) {Magoosh, Majortest}",
    ],
    "Genuine": [
        "Authentic",
        "Legitimate",
        "Veritable {Magoosh, Majortest}",
        "Counterfeit(opposite) {Majortest}",
        "Factitious(opposite) {Barron, Magoosh}",
        "bona",
    ],
    "Environment": [
        "habitat",
    ],
    "Gloomy Or Dark": [
        "Bleak {Magoosh}",
        "Somber {Barron}",
        "cadaverous",
        "doleful",
        "dolorous",
        "elegiac",
        "lachrymose",
    ],
    "Gloomy Or Dark (Wan)": [
        "wan",
    ],
    "Illogical Or Strange": [
        "Absurd {Barron}",
        "Atypical {Barron}",
        "Bizarre {Barron}",
        "Ludicrous {Majortest}",
        "Outlandish",
        "Preposterous",
        "Uncanny {Magoosh}",
        "incompatibility",
        "incongruous",
    ],
    "Immature": [
        "Callow {Barron, Magoosh, Majortest}",
        "Puerile {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
    ],
    "Accommodate": [
        "accommodate",
    ],
    "Native Or Local": [
        "Indigenous {Barron, Magoosh, Majortest}",
        "Exotic(opposite)",
        "domicile",
        "milieu",
    ],
    "Puzzling": [
        "Conundrum {Magoosh, Majortest, Manhattan}",
        "Cryptic {Barron, Magoosh, Majortest}",
        "Enigma {Barron, Kaplan, Majortest, Manhattan}",
        "Garble {Majortest}",
        "Inscrutable {Magoosh, Majortest}",
        "Intrigue",
        "Labyrinth {Barron, Majortest}",
        "Maze",
        "hodgepodge",
        "imbroglio",
    ],
    "Puzzling (Sharp Rod)": [
        "spear",
    ],
    "Rude": [
        "Boor {Kaplan, Majortest, Manhattan}",
        "Brusque {Majortest}",
        "Curt",
        "Terse {Barron, Majortest, Manhattan, Princeton}",
        "arrant",
        "audacity",
        "boorish",
        "brusquely",
        "cavalier",
        "philistine",
        "raffish",
        "scurrilous",
        "insufferable",
    ],
    "Prudent": [
        "discreet",
    ],
    "Rule": [
        "criterion",
    ],
    "Shy Or Introvert": [
        "Coy",
        "Diffidence",
        "Reserved",
        "Retiring {Magoosh}",
        "Timid",
        "Timorous {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "confidant",
        "diffident",
        "self-effacing",
    ],
    "Shy Or Introvert (Uncooperative)": [
        "unforthcoming",
    ],
    "Unintentionally": [
        "Inadvertently",
        "Unwittingly",
        "inadvertent",
    ],
    "Emotional": [
        "demonstrative",
        "maudlin",
        "mawkish",
        "sentimental",
    ],
    "Widespread(-)": [
        "Epidemic",
        "Pandemic",
        "Rampant {Barron}",
        "Endemic(opposite) {Kaplan, Magoosh, Manhattan, Princeton}",
        "Rife {Barron, Majortest, Manhattan}",
        "indiscriminate",
    ],
    "Widespread (Fashion)": [
        "vogue",
    ],
    "Widespread OR Inflammable": [
        "inflammable",
    ],
    "Working Under Another": [
        "Subordinate",
        "Underling",
        "menial",
    ],
}