# Auto-updated Jamboree list: list1

list1 = {
    "Attractive": [
        "Aesthetic {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Comely {Barron}",
        "debonair",
    ],
    "Productive": [
        "fecund",
    ],
    "Avodi OR Dodge": [
        "Avert {Magoosh}",
        "Circumvent {Magoosh, Majortest}",
        "Deflect {Manhattan}",
        "Elude/Elusive {Magoosh}",
        "Evade OR Evasive",
        "Parry {Kaplan, Majortest, Manhattan}",
        "Shirk {Majortest}",
        "Shunt",
        "Skirt {Manhattan}",
        "Swerve",
        "Quibble {Majortest, Manhattan}",
        "Head-On(Opposite)",
        "Inevitable(Opposite) {Barron, Majortest}",
        "Unavoidable(Opposite)",
    ],
    "Awkward OR Clumsy": [
        "Fumble",
        "Gauche {Magoosh, Manhattan}",
        "Gawky {Manhattan}",
        "Ungainly",
        "bumbling",
        "gaffe",
    ],
    "Be Slow OR Waste Of Time": [
        "Dally {Majortest}",
        "Dilatory {Kaplan, Magoosh, Majortest, Manhattan}",
        "Dawdle",
        "Dilly Dally",
        "Laggard",
        "Linger",
        "Malinger {Kaplan, Majortest, Manhattan}",
    ],
    "Detailed Knowledge OR Intellectual": [
        "Cerebral {Magoosh, Majortest}",
        "Erudite {Barron, Kaplan, Magoosh, Manhattan, Princeton}",
        "Pundit {Magoosh, Majortest}",
        "elaborate",
        "empiricism",
        "rationalize",
        "engrossed",
    ],
    "Flexible": [
        "Limber",
        "Lithe {Barron, Majortest}",
        "Nimble",
        "Supple",
        "malleable",
        "docile",
    ],
    "Flexible (Docile)": [
        "tractable",
    ],
    "Foolish Talk": [
        "Babble",
        "Blather",
        "Drawl {Majortest}",
        "Drivel {Majortest}",
        "Gibberish",
        "Jabber",
        "Nonsensical",
        "Prate",
        "Prattle {Kaplan, Majortest, Manhattan, Princeton}",
        "epigram",
        "bromide",
        "palaver",
        "quip",
        "raillery",
        "ribald",
    ],
    "Foolish Talk (Bragging)": [
        "vain",
    ],
    "Having Twists OR Turns": [
        "Circuitous {Majortest}",
        "Convoluted {Kaplan, Magoosh, Manhattan, Princeton}",
        "Intertwined",
        "Involved {Magoosh}",
        "Meander {Magoosh, Majortest}",
        "Sinuous",
        "Tortuous {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "byzantine",
        "metamorphosis",
        "protean",
        "transmute",
    ],
    "Having Twists OR Turns (Change)": [
        "vicissitude",
    ],
    "Horrifying OR Shocking": [
        "Aghast",
        "Appalling",
        "Egregious {Barron, Magoosh, Majortest, Manhattan}",
        "Ghastly",
        "Grisly",
        "Gross",
        "Grotesque {Barron}",
        "Gruesome",
        "Heinous {Barron}",
        "Hideous",
        "Horrendous",
        "Monstrous",
        "Morbid",
        "Unsightly",
        "Vile",
        "macabre",
    ],
    "Inclination": [
        "Affinity",
        "Aptitude",
        "Bent {Majortest, Manhattan, Princeton}",
        "Disposed",
        "Penchant {Barron, Majortest, Manhattan}",
        "Predilection {Magoosh, Majortest, Manhattan, Princeton}",
        "Predisposition",
        "Proclivity {Kaplan, Majortest, Manhattan, Princeton}",
        "Propensity {Barron, Majortest, Manhattan, Princeton}",
    ],
    "Ineffective": [
        "Futile {Majortest, Manhattan}",
        "Ineffectual {Barron}",
        "Efficacy(Opposite) {Barron, Kaplan, Majortest, Manhattan}",
        "Feckless {Magoosh, Majortest}",
        "abortive",
        "neutralize",
        "nullify",
        "stultify",
    ],
    "Ineffective (Unviable)": [
        "unviable",
    ],
    "Optimistic": [
        "Buoyant",
        "Sanguine {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "pollyannaish",
    ],
    "Optimistic/Cheerful": [
        "jaunty",
    ],
    "Prediction": [
        "Augur OR Augury",
        "Forecast",
        "Foresight OR Foresee",
        "Foretell",
        "Presage {Majortest}",
        "Prescience {Majortest, Princeton}",
        "Prognosis",
        "checkered",
        "prescient",
        "presentiment",
        "prognosticate",
        "prognostication",
    ],
    "Opinion": [
        "deem",
    ],
    "Separate OR Not Connected": [
        "Disjointed {Manhattan}",
        "Polarize",
        "Segregated",
        "Nexus(Opposite) {Majortest}",
        "discrete",
        "dispersed",
        "dissipate",
        "pariah",
        "remote",
    ],
    "Sign(Warning) (-)": [
        "Forebode",
        "Foreshadow {Manhattan}",
        "Portend {Majortest}",
        "Portent {Majortest}",
        "Premonition {Barron}",
    ],
    "Skillful": [
        "Adept",
        "Adroit {Barron, Majortest}",
        "Agile",
        "Consummate {Barron, Magoosh, Majortest}",
        "Deft",
        "Dexterous {Majortest}",
        "Proficient",
        "Prowess",
        "Inept(Opposite) {Majortest}",
        "Maladroit(Opposite) {Magoosh, Majortest}",
        "charisma",
        "dexterity",
        "ingenuity",
        "potent",
        "resourceful",
        "virtuosity",
        "genteel",
    ],
    "Skillful (Refined)": [
        "urbane",
    ],
    "Spread": [
        "Diffuse {Manhattan}",
        "Disseminate {Barron, Magoosh, Manhattan}",
        "Promulgate {Barron, Magoosh}",
        "Propagate {Barron, Manhattan}",
        "nomadic",
        "peripatetic",
        "permeate",
        "prevalent",
        "glean",
        "prevail",
    ],
    "Threatening": [
        "Ominous {Barron, Majortest}",
        "Sinister {Barron}",
        "Intimidate {Barron}",
        "browbeat",
        "cow",
        "hector",
    ],
    "To do with teaching": [
        "Pedantic {Magoosh, Majortest, Princeton}",
        "Didactic {Magoosh, Majortest, Manhattan, Princeton}",
        "Sophist",
        "behooves",
        "indoctrinate",
        "mentor",
        "nurture",
        "pedagogue",
        "pedagogy",
    ],
    "Very Angry": [
        "Enrage",
        "Fume",
        "Glower {Kaplan, Manhattan}",
        "Incense {Magoosh}",
        "Infuriate",
        "Irate {Barron}",
        "Ire {Majortest}",
        "Livid {Barron, Kaplan, Majortest, Manhattan}",
        "Rabid {Barron}",
        "Seethe",
        "Smolder",
        "Wrath",
        "besotted",
        "bristle",
        "indignant",
    ],
    "Very Angry (Violent Woman)": [
        "virago",
    ],
    "Very Angry (Offended)": [
        "umbrage",
    ],
    "Very Angry/Injustice": [
        "indignant",
    ],
    "Heyday": [
        "heyday",
    ],
    "Very Talent(Child)": [
        "Prodigy {Barron}",
        "Precocious {Barron, Magoosh, Majortest}",
        "diabolical",
    ],
}