# Auto-updated Jamboree list: list12

list12 = {
    "Desiring Only Pleasure": [
        "Hedonist {Majortest, Manhattan}",
        "Sybarite {Kaplan, Magoosh, Majortest, Manhattan}",
        "desideratum",
        "pine",
        "yearn",
        "yen",
    ],
    "Dramatic Behavior": [
        "Histrionic {Barron, Magoosh, Majortest}",
        "Melodramatic",
        "antic",
    ],
    "Dramatic Behavior (Pompous)": [
        "turgid",
    ],
    "Exclude OR Forbid": [
        "Ostracize {Barron, Magoosh}",
        "Shun",
        "Taboo {Barron}",
        "banish",
        "censor",
        "eschew",
    ],
    "Exclude OR Forbid (Reject)": [
        "snub",
    ],
    "Frank": [
        "Candid OR Candor {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Forthright {Barron, Magoosh}",
        "Vocal",
        "blunt",
        "candidness",
        "candor",
        "forthcoming",
    ],
    "Fray": [
        "fray",
    ],
    "Fully Satisfied": [
        "Gratify",
        "Quench",
        "Replete {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Satiate {Kaplan, Majortest, Manhattan}",
        "Saturate {Barron, Manhattan}",
        "Suffice",
        "satiety",
    ],
    "Fussy(-)": [
        "Finicky",
        "Nitpicking",
        "Persnickety {Majortest}",
        "Squeamish {Barron}",
        "Stickler {Majortest}",
        "provident",
    ],
    "Hint OR Indirect Reference": [
        "Allude OR Allusion {Barron}",
        "Cue",
        "Implicit {Manhattan}",
        "Innuendo",
        "Insinuate {Manhattan}",
        "Tacit {Barron, Kaplan, Manhattan, Princeton}",
        "Blatant (Opposite) {Barron, Magoosh, Majortest}",
        "Explicit (Opposite) {Kaplan, Manhattan}",
        "Cite (Opposite)",
        "feint",
        "intimate",
        "intimation",
    ],
    "Huge OR Big": [
        "Behemoth",
        "Colossal {Magoosh}",
        "Gargantuan",
        "Gigantic",
        "Humongous",
        "Mammoth {Barron}",
        "Monolithic {Barron, Majortest}",
        "Monumental",
        "Prodigious {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Titanic",
        "Towering",
        "Voluminous {Barron, Majortest}",
        "commodious",
        "conflagration",
        "enormity",
    ],
    "Insignificant": [
        "Marginal",
        "Minute",
        "Negligible {Magoosh}",
        "Paltry {Barron}",
        "Token {Manhattan}",
        "Trifle",
        "dregs",
    ],
    "Lacking": [
        "Bereft {Barron, Magoosh}",
        "Deprived",
        "Devoid",
        "Wanting {Magoosh}",
        "crave",
        "exiguity",
        "insatiable",
    ],
    "Long Essay OR Speech": [
        "Discourse",
        "Dissertation",
        "Rhetoric {Barron, Kaplan, Manhattan, Princeton}",
        "litany",
    ],
    "Minor DIfferences": [
        "Nuances",
        "Subtle {Majortest, Princeton}",
        "Shades",
        "differentiate",
        "nuance",
    ],
    "Split OR Gap (Difference)": [
        "variance",
    ],
    "Mistake OR Act Done Carelessly": [
        "Botch",
        "Bungle",
        "Misnomer {Majortest}",
        "Tactless",
        "Finesse (Opposite) {Majortest, Manhattan}",
        "err",
        "misattribute",
        "misconstrue",
        "solecism",
    ],
    "Talk Aimlessly": [
        "maunder",
    ],
    "Pertaining To Religion": [
        "Agnostic",
        "Atheist {Majortest}",
        "Pious {Majortest, Manhattan, Princeton}",
        "Proselytize {Magoosh}",
        "Theist",
        "Theology",
        "devout",
    ],
    "Pertaining To Home": [
        "edifice",
    ],
    "Place Side By Side": [
        "Abut {Majortest}",
        "Adjacent",
        "Contiguous {Majortest, Princeton}",
        "Juxtaposition",
        "juxtapose",
        "interject",
    ],
    "Place (Sacred)": [
        "sanctuary",
    ],
    "Remove OR Destroy": [
        "Annihilate",
        "Decimate {Majortest}",
        "Efface {Majortest}",
        "Eradicate {Barron, Magoosh}",
        "Expunge {Barron, Magoosh}",
        "Exterminate",
        "Extirpate {Majortest, Princeton}",
        "Obliterate {Barron, Majortest}",
        "Perish",
        "Raze {Barron, Majortest}",
        "Indelible (Opposite) {Majortest}",
        "Devastate",
        "Excise",
        "dismantle",
        "jettison",
        "obviate",
        "oust",
        "truncate",
    ],
    "Remove OR Destroy (Sneaky)": [
        "supplant",
    ],
    "Small": [
        "Slight {Majortest, Manhattan}",
        "Minuscule",
        "Infinitesimal",
        "Diminutive {Barron, Magoosh}",
    ],
    "Stigma": [
        "stigma",
    ],
    "Strengthen OR Support": [
        "Bastion {Majortest}",
        "Bolster {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Buttress {Magoosh, Majortest, Manhattan}",
        "Fortify {Manhattan}",
        "Prime",
        "Prop",
        "aegis",
        "appurtenant",
        "bulwark",
        "replenish",
    ],
    "Strengthen OR Support (Financial)": [
        "underwrite",
    ],
    "Sympathy": [
        "Compassion {Barron}",
        "Empathy",
        "Callous (Opposite) {Barron}",
        "condolence",
        "empathetic",
        "pathetic",
    ],
    "Match": [
        "dovetail",
    ],
    "Theory Without Evidence": [
        "Hypothetical",
        "Speculate {Manhattan}",
        "Empirical (Opposite) {Majortest, Manhattan, Princeton}",
        "chimera",
        "chimerical",
        "phantasmagorical",
        "potential",
    ],
    "Thorough OR Precise": [
        "Conscientious",
        "Fastidious {Barron, Magoosh, Majortest, Manhattan}",
        "Meticulous {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Nice {Princeton}",
        "Punctilious {Magoosh, Majortest}",
        "Purist {Majortest}",
        "Scrupulous {Magoosh, Majortest}",
        "decorum",
        "delineate",
        "delineation",
        "thoroughgoing",
    ],
    "To Do Happily (+)": [
        "Alacrity {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Obliging {Magoosh}",
        "chivalrous",
        "palatable",
        "piquant",
        "succulent",
    ],
    "To Do Reluctantly OR Unwillingly (-)": [
        "Balk {Barron, Magoosh, Majortest, Manhattan}",
        "Grudging",
        "deign",
        "loath",
        "resignation",
    ],
    "To Do Reluctantly OR Unwillingly (-) (Inconvenient)": [
        "untoward",
    ],
    "To Guess OR Infer": [
        "Conjecture {Barron}",
        "Construe {Barron, Magoosh, Manhattan}",
        "Deduce",
        "Extrapolate {Majortest, Manhattan}",
        "Surmise {Barron, Manhattan}",
        "Inductive",
        "elicit",
        "posit",
        "presumption",
    ],
    "Understand": [
        "Apprehend",
        "Assimilate",
        "Comprehend",
        "Fathom {Manhattan}",
        "Intelligible {Majortest, Manhattan}",
        "Illegible (Opposite)",
        "cope",
        "fathom",
    ],
    "Rude (Standard)": [
        "unseemly",
    ],
    "Used To": [
        "Habituate",
        "Immune",
        "Inure {Kaplan, Magoosh, Manhattan}",
        "Inveterate {Barron, Magoosh, Majortest, Princeton}",
        "brook",
    ],
    "Used To (Absorb)": [
        "soak",
    ],
    "Trust": [
        "credulity",
    ],
    "Weak OR Fragile": [
        "Flimsy",
        "Frail {Barron}",
        "Intangible {Majortest}",
        "Tenuous {Majortest, Manhattan, Princeton}",
        "Palpable (Opposite) {Majortest}",
        "Substantial (Opposite)",
        "Tactile (Opposite) {Majortest}",
        "Corporeal",
        "decrepit",
        "dilapidated",
        "emaciated",
        "mortality",
        "pathetic",
        "senile",
        "tremulous",
        "doddering",
        "gaunt",
    ],
    "Fake Or False": [
        "disingenuous",
    ],
    "Weaken": [
        "Erode",
        "Undercut",
        "Undermine {Barron, Magoosh, Majortest, Manhattan}",
        "Subvert",
        "Undergird (Opposite) {Majortest}",
        "attenuated",
    ],
}