# Auto-updated Jamboree list: list7

list7 = {
    "Boring and Repetitious": [
        "Monotonous {Majortest}",
        "Plod",
        "Tedious",
        "drudgery",
    ],
    "Clear ( Both Physically and in Meaning)": [
        "Clarity",
        "Elucidate {Barron, Magoosh, Majortest}",
        "Exposition {Majortest}",
        "Expound {Magoosh}",
        "Limpid {Kaplan, Magoosh, Majortest, Manhattan}",
        "Lucid {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Pellucid {Magoosh, Majortest, Manhattan, Princeton}",
    ],
    "Correct OR Repair": [
        "Amend",
        "Atone",
        "Disabuse {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Expiate {Majortest, Princeton}",
        "Indemnify",
        "Redemption",
        "Redress {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Reparation",
        "Restitution",
        "compensate",
        "modify",
    ],
    "Difficult": [
        "Arduous {Magoosh, Majortest, Manhattan, Princeton}",
        "Cumbersome {Barron, Magoosh, Majortest}",
        "Encumber {Magoosh}",
        "Exacting {Magoosh, Manhattan}",
        "Onerous {Kaplan, Majortest, Manhattan, Princeton}",
        "Ponderous {Magoosh, Majortest, Manhattan}",
        "Facile(Opposite) {Barron, Magoosh}",
        "Laborious",
        "precipitous",
        "taxing",
    ],
    "Difficult (Handled)": [
        "unwieldy",
    ],
    "Difficult (Agony)": [
        "travail",
    ],
    "Efficacious": [
        "efficacious",
    ],
    "Difficulty OR Confusing Situation": [
        "Dilemma {Majortest}",
        "Plight {Barron}",
        "Predicament {Majortest}",
        "Quandary {Barron, Magoosh, Majortest, Manhattan}",
        "encumbrance",
    ],
    "Difficult (Falling Sensation)": [
        "vertigo",
    ],
    "Disloyalty": [
        "Betray {Magoosh}",
        "Perfidy {Majortest, Princeton}",
        "Fealty(Opposite)",
        "Fidelity(Opposite) {Manhattan}",
        "apostate",
        "perfidious",
    ],
    "Experienced": [
        "Seasoned",
        "Veteran",
    ],
    "Experienced (Skill in Stories)": [
        "raconteur",
    ],
    "Expert": [
        "Connoisseur {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Layperson(Opposite) {Manhattan}",
        "Virtuoso {Majortest}",
        "capable",
    ],
    "Feeling Guilty": [
        "Contrite {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Penitent {Barron, Manhattan}",
        "Remorse {Majortest}",
        "Rueful",
        "contrition",
        "repent",
        "rue",
    ],
    "Longevity": [
        "longevity",
    ],
    "Happening Before Main Event": [
        "Antecedent",
        "Forerunner",
        "Harbinger {Barron}",
        "Precedent {Barron, Magoosh, Majortest}",
        "Precursor {Manhattan, Princeton}",
        "Antedate {Magoosh, Manhattan}",
        "prelude",
    ],
    "Harmful OR Curse": [
        "Anathema {Barron, Magoosh, Princeton}",
        "Baleful {Magoosh, Majortest}",
        "Bane {Barron, Majortest, Manhattan}",
        "Blight {Kaplan, Manhattan}",
        "Deleterious {Barron, Kaplan, Magoosh, Majortest, Manhattan}",
        "Detrimental {Magoosh, Majortest}",
        "Malediction {Kaplan, Majortest, Manhattan}",
        "Malignant {Barron}",
        "Pernicious {Barron, Magoosh, Majortest, Manhattan, Princeton}",
        "Insidious {Barron, Magoosh}",
        "detriment",
        "fell",
        "lethal",
    ],
    "Harmful OR Curse (Toxin)": [
        "venom",
    ],
    "Idealistic": [
        "Quixotic {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Utopian {Majortest}",
        "hagiographic",
        "idyllic",
    ],
    "Immoral": [
        "Debauchery",
        "Decadent",
        "Degenerate",
        "Depravity {Majortest}",
        "Dissolute",
        "Improbity {Majortest}",
        "Wayward",
        "decadence",
        "dissolution",
        "iniquity",
        "reprobate",
    ],
    "Immoral (Offensive)": [
        "unsavory",
    ],
    "Immoral (Practice)": [
        "turpitude",
    ],
    "Interval OR Pause": [
        "Abeyance {Kaplan, Majortest, Manhattan}",
        "Hiatus {Majortest}",
        "Lull {Manhattan}",
        "Moratorium {Majortest}",
        "Respite {Barron, Magoosh, Majortest}",
    ],
    "Just Beginning OR Developing": [
        "Embryonic {Magoosh}",
        "Fledgling {Barron, Magoosh, Manhattan}",
        "Inchoate {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Incipient {Barron, Majortest, Manhattan, Princeton}",
        "Nascent {Barron, Kaplan, Majortest, Manhattan, Princeton}",
        "Rudimentary {Barron, Magoosh, Manhattan}",
    ],
    "Lose Strength OR Weaken": [
        "Atrophy {Barron, Majortest}",
        "Attenuate {Kaplan, Magoosh, Majortest, Manhattan}",
        "Attrition",
        "Debilitate {Barron}",
        "Degenerate",
        "Degradation {Majortest}",
        "Effete",
        "Enervate {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Enfeeble",
        "Flagging",
        "Sup",
        "Wilt",
        "Wither",
    ],
    "Restrain OR Set Free (Opposite)": [
        "Bridle {Magoosh}",
        "Circumscribe {Magoosh, Majortest, Manhattan}",
        "Constraint {Magoosh}",
        "Fetter {Barron}",
        "Rein",
        "Secure {Majortest}",
        "Shackle",
        "Extricate(Opposite)",
        "Manacle",
        "Emancipate(Opposite) {Majortest}",
    ],
    "Right To Vote": [
        "Enfranchise {Majortest}",
        "Suffrage",
        "disenfranchise",
    ],
    "Strange": [
        "Eccentric {Magoosh, Majortest, Manhattan, Princeton}",
        "Foible {Magoosh, Majortest}",
        "Idiosyncrasy {Kaplan, Magoosh, Majortest, Manhattan}",
        "Quirkiness",
        "peculiar",
    ],
    "Hamstrung": [
        "hamstrung",
    ],
    "Summary": [
        "Crux",
        "Gist {Majortest, Manhattan}",
        "Precis {Kaplan}",
        "Purport",
        "Synopsis",
        "denouement",
    ],
    "Thriving OR Restored": [
        "Burgeon {Barron, Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Regenerate",
        "Rejuvenate",
        "Resuscitation {Majortest}",
        "Revive",
        "crystallize",
    ],
    "Unclear OR Hazy": [
        "Amorphous {Magoosh, Majortest}",
        "Becloud",
        "Cloud",
        "Indistinct",
        "Murky {Barron}",
        "Nebulous {Barron, Majortest, Princeton}",
    ],
    "Without Mistakes OR Perfect": [
        "Flawless",
        "Immaculate",
        "Impeccable {Barron, Magoosh}",
        "Infallible {Barron, Majortest, Manhattan}",
        "Integrity",
        "Irreproachable {Majortest}",
        "Probity {Kaplan, Magoosh, Majortest, Manhattan, Princeton}",
        "Rectitude",
        "Unimpeachable {Magoosh}",
        "pristine",
        "utopia",
    ],
}